# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'it.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(503, 409)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("/*Symmetry Melody 2*/\n"
"/* Estilo para todos los elementos */\n"
"\n"
"* {\n"
"    background-image: url(:/fondo/noise.png);\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-image: url(:/fondo/noise.png);\n"
"    color: white;\n"
"    font-size: 15px;\n"
"    width: 180px;\n"
"    height: 25px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Estilo para el encabezado de la tabla */\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Estilo para QLineEdit y QPushButton */\n"
"\n"
"QLineEdit, QPushButton {\n"
"    font: 11pt;\n"
"    border: 1px solid gray;\n"
"    border-radius: 7px;\n"
"    background-image: url(:/fondo/noise.png);\n"
"}\n"
"\n"
"/* Estilo para QLineEdit cuando el mouse está sobre él */\n"
"QLineEdit:hover {\n"
"    border: 2px solid white;\n"
"    background-image: url(:/fondo/noise.png);\n"
"}\n"
"\n"
"/* Estilo para QLineEdit cuando pierde el foco */\n"
"QLineEdit:focus {\n"
"    border: 2px solid gray;\n"
"    background-image: url(:/fondo/noise.png);\n"
"}\n"
"\n"
"/* Estilo para QFrame */\n"
"QFrame {\n"
"    border-radius: 3px;\n"
"    background-image: url(:/fondo/noise.png);\n"
"}\n"
"\n"
"/* Estilo para QSlider */\n"
"\n"
"QSlider {\n"
"    background-image: url(:/fondo/noise.png);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px;\n"
"    background: #bbb;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #777;\n"
"    width: 15px;\n"
"    margin-top: -2px;\n"
"    margin-bottom: -2px;\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 57))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.descargar = QtWidgets.QPushButton(self.frame)
        self.descargar.setObjectName("descargar")
        self.horizontalLayout.addWidget(self.descargar)
        self.play_pause = QtWidgets.QPushButton(self.frame)
        self.play_pause.setObjectName("play_pause")
        self.horizontalLayout.addWidget(self.play_pause)
        self.url = QtWidgets.QLineEdit(self.frame)
        self.url.setClearButtonEnabled(True)
        self.url.setObjectName("url")
        self.horizontalLayout.addWidget(self.url)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lista = QtWidgets.QTableWidget(self.frame_3)
        self.lista.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista.setObjectName("lista")
        self.lista.setColumnCount(1)
        self.lista.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.lista.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lista.setItem(0, 0, item)
        self.lista.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.lista)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(107, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info = QtWidgets.QTextEdit(self.groupBox_2)
        self.info.setObjectName("info")
        self.verticalLayout_3.addWidget(self.info)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 140))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.indices = QtWidgets.QRadioButton(self.groupBox)
        self.indices.setObjectName("indices")
        self.verticalLayout_4.addWidget(self.indices)
        self.ver_reso = QtWidgets.QLabel(self.groupBox)
        self.ver_reso.setObjectName("ver_reso")
        self.verticalLayout_4.addWidget(self.ver_reso)
        self.ajustar_reso = QtWidgets.QSlider(self.groupBox)
        self.ajustar_reso.setMinimum(1)
        self.ajustar_reso.setMaximum(10)
        self.ajustar_reso.setSingleStep(7)
        self.ajustar_reso.setSliderPosition(7)
        self.ajustar_reso.setOrientation(QtCore.Qt.Horizontal)
        self.ajustar_reso.setInvertedControls(False)
        self.ajustar_reso.setObjectName("ajustar_reso")
        self.verticalLayout_4.addWidget(self.ajustar_reso)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAbrir_Proyecto = QtWidgets.QAction(MainWindow)
        self.actionAbrir_Proyecto.setObjectName("actionAbrir_Proyecto")
        self.actionGuardar_como = QtWidgets.QAction(MainWindow)
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionExportar_mid = QtWidgets.QAction(MainWindow)
        self.actionExportar_mid.setObjectName("actionExportar_mid")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionBuscador_de_ritmas = QtWidgets.QAction(MainWindow)
        self.actionBuscador_de_ritmas.setObjectName("actionBuscador_de_ritmas")
        self.actionFuerza_burta_euclideana = QtWidgets.QAction(MainWindow)
        self.actionFuerza_burta_euclideana.setObjectName("actionFuerza_burta_euclideana")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionDame_un_caf = QtWidgets.QAction(MainWindow)
        self.actionDame_un_caf.setObjectName("actionDame_un_caf")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionSobre_el_Proyecto = QtWidgets.QAction(MainWindow)
        self.actionSobre_el_Proyecto.setObjectName("actionSobre_el_Proyecto")
        self.action_sostenido = QtWidgets.QAction(MainWindow)
        self.action_sostenido.setObjectName("action_sostenido")
        self.actionb_bemol = QtWidgets.QAction(MainWindow)
        self.actionb_bemol.setObjectName("actionb_bemol")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_tresillo_largo = QtWidgets.QAction(MainWindow)
        self.action_tresillo_largo.setObjectName("action_tresillo_largo")
        self.action4_in_1_sonido_RRR = QtWidgets.QAction(MainWindow)
        self.action4_in_1_sonido_RRR.setObjectName("action4_in_1_sonido_RRR")
        self.action8_in_1_sonido_rrr = QtWidgets.QAction(MainWindow)
        self.action8_in_1_sonido_rrr.setObjectName("action8_in_1_sonido_rrr")
        self.actionFuerza_Bruta_Euclideana_Brick = QtWidgets.QAction(MainWindow)
        self.actionFuerza_Bruta_Euclideana_Brick.setObjectName("actionFuerza_Bruta_Euclideana_Brick")
        self.actionFuerza_Bruta_Euclideana_Brick_2 = QtWidgets.QAction(MainWindow)
        self.actionFuerza_Bruta_Euclideana_Brick_2.setObjectName("actionFuerza_Bruta_Euclideana_Brick_2")
        self.actionHarmonia_negativa = QtWidgets.QAction(MainWindow)
        self.actionHarmonia_negativa.setObjectName("actionHarmonia_negativa")
        self.actionQuitar_numeros = QtWidgets.QAction(MainWindow)
        self.actionQuitar_numeros.setObjectName("actionQuitar_numeros")
        self.actionSeparar_en_silabras = QtWidgets.QAction(MainWindow)
        self.actionSeparar_en_silabras.setObjectName("actionSeparar_en_silabras")
        self.actionCopiar_Letra = QtWidgets.QAction(MainWindow)
        self.actionCopiar_Letra.setObjectName("actionCopiar_Letra")
        self.actionConfiguraci_n_2 = QtWidgets.QAction(MainWindow)
        self.actionConfiguraci_n_2.setObjectName("actionConfiguraci_n_2")
        self.actionJonico_mayor = QtWidgets.QAction(MainWindow)
        self.actionJonico_mayor.setObjectName("actionJonico_mayor")
        self.actionEolico_Menor = QtWidgets.QAction(MainWindow)
        self.actionEolico_Menor.setObjectName("actionEolico_Menor")
        self.actionMenor_Harmonica = QtWidgets.QAction(MainWindow)
        self.actionMenor_Harmonica.setObjectName("actionMenor_Harmonica")
        self.actionFrigio = QtWidgets.QAction(MainWindow)
        self.actionFrigio.setObjectName("actionFrigio")
        self.actionDorico = QtWidgets.QAction(MainWindow)
        self.actionDorico.setObjectName("actionDorico")
        self.actionMixolidio = QtWidgets.QAction(MainWindow)
        self.actionMixolidio.setObjectName("actionMixolidio")
        self.actionArabe = QtWidgets.QAction(MainWindow)
        self.actionArabe.setObjectName("actionArabe")
        self.actionLocrio = QtWidgets.QAction(MainWindow)
        self.actionLocrio.setObjectName("actionLocrio")
        self.actionHungara = QtWidgets.QAction(MainWindow)
        self.actionHungara.setObjectName("actionHungara")
        self.actionLidio = QtWidgets.QAction(MainWindow)
        self.actionLidio.setObjectName("actionLidio")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hyper Tube"))
        self.descargar.setText(_translate("MainWindow", "Descargar"))
        self.play_pause.setText(_translate("MainWindow", "Play"))
        self.url.setPlaceholderText(_translate("MainWindow", "Pega una url"))
        self.lista.setSortingEnabled(False)
        item = self.lista.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "hi"))
        item = self.lista.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "hi"))
        __sortingEnabled = self.lista.isSortingEnabled()
        self.lista.setSortingEnabled(False)
        item = self.lista.item(0, 0)
        item.setText(_translate("MainWindow", "Video de prueba"))
        self.lista.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("MainWindow", "Info"))
        self.info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nombre: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Peso: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">bajado:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#00ff00;\">Listo!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuración"))
        self.indices.setText(_translate("MainWindow", "Nombres 1, 2, 3 en listas"))
        self.ver_reso.setText(_translate("MainWindow", "Resolución: 720p"))
        self.actionAbrir_Proyecto.setText(_translate("MainWindow", "Abrir Proyecto"))
        self.actionGuardar_como.setText(_translate("MainWindow", "Guardar como"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionExportar_mid.setText(_translate("MainWindow", "Exportar .mid"))
        self.actionSalir.setText(_translate("MainWindow", "Exportar Mp3"))
        self.actionBuscador_de_ritmas.setText(_translate("MainWindow", "Buscador de ritmas"))
        self.actionFuerza_burta_euclideana.setText(_translate("MainWindow", "3 in 4 (tresillo corto)"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionDame_un_caf.setText(_translate("MainWindow", "Dame un café <3"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))
        self.actionSobre_el_Proyecto.setText(_translate("MainWindow", "Sobre el Proyecto"))
        self.action_sostenido.setText(_translate("MainWindow", "# (sostenido)"))
        self.actionb_bemol.setText(_translate("MainWindow", "♭ (bemol)"))
        self.action_3.setText(_translate("MainWindow", "𝅘𝅥𝅮 (tresillo coto)"))
        self.action_tresillo_largo.setText(_translate("MainWindow", "𝅘𝅥 (tresillo largo)"))
        self.action4_in_1_sonido_RRR.setText(_translate("MainWindow", "4 in 1 (sonido RRR)"))
        self.action8_in_1_sonido_rrr.setText(_translate("MainWindow", "8 in 1 (sonido rrr)"))
        self.actionFuerza_Bruta_Euclideana_Brick.setText(_translate("MainWindow", "Silencio (todo deja de sonar)"))
        self.actionFuerza_Bruta_Euclideana_Brick_2.setText(_translate("MainWindow", "Fuerza Bruta Euclideana Brick"))
        self.actionHarmonia_negativa.setText(_translate("MainWindow", "Harmonia negativa"))
        self.actionQuitar_numeros.setText(_translate("MainWindow", "Quitar numeros"))
        self.actionSeparar_en_silabras.setText(_translate("MainWindow", "Separar en silabras"))
        self.actionCopiar_Letra.setText(_translate("MainWindow", "Copiar Letra"))
        self.actionConfiguraci_n_2.setText(_translate("MainWindow", "Configuración"))
        self.actionJonico_mayor.setText(_translate("MainWindow", "Jonico/Mayor 🌻"))
        self.actionEolico_Menor.setText(_translate("MainWindow", "Eolico/Menor 🌧"))
        self.actionMenor_Harmonica.setText(_translate("MainWindow", "Menor Harmonica"))
        self.actionFrigio.setText(_translate("MainWindow", "Frigio"))
        self.actionDorico.setText(_translate("MainWindow", "Dorico"))
        self.actionMixolidio.setText(_translate("MainWindow", "Mixolidio"))
        self.actionArabe.setText(_translate("MainWindow", "Arabe"))
        self.actionLocrio.setText(_translate("MainWindow", "Locrio"))
        self.actionHungara.setText(_translate("MainWindow", "Hungara"))
        self.actionLidio.setText(_translate("MainWindow", "Lidio"))
import it_rc
